[technote]
id = "SQR-087"
series_id = "SQR"
canonical_url = "https://sqr-087.lsst.io"
github_url = "https://github.com/lsst-sqre/sqr-087"
github_default_branch = "main"
date_created = 2024-06-04T23:28:37Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Frossie"
name.family = "Economou"
internal_id = "economouf"
orcid = "https://orcid.org/0000-0002-8333-7615"
[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "950 N. Cherry Ave., Tucson, AZ 85719, USA"
